import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const cfg = { url: window.SUPABASE_URL, key: window.SUPABASE_ANON_KEY };
const configured = cfg.url && cfg.key && !cfg.url.includes('YOUR-PROJECT') && !cfg.key.includes('YOUR_SUPABASE');
const sb = configured ? createClient(cfg.url, cfg.key) : null;
const ADMIN_EMAIL = window.ADMIN_EMAIL || 'admin@penyuluh.local';
let cache = { groups: [], agenda: [], kegiatan_kua: [], materials: [], reports: [], gallery: [], profile: null };
const $ = id => document.getElementById(id);

function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function showToast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>$('toast').classList.remove('show'),3500)}
window.showToast=showToast;
function fail(e){console.error(e);showToast(e?.message||'Terjadi kesalahan.');}
function toggleNav(){$('nav').classList.toggle('open')} window.toggleNav=toggleNav;
function openLogin(){$('adminEmail').value=ADMIN_EMAIL;$('loginModal').classList.add('open');$('adminPass').focus()} window.openLogin=openLogin;
function closeLogin(){$('loginModal').classList.remove('open')} window.closeLogin=closeLogin;
function closeAdmin(){$('adminModal').classList.remove('open')} window.closeAdmin=closeAdmin;
function closeRead(){$('readModal').classList.remove('open')} window.closeRead=closeRead;

async function requireConfigured(){if(!configured){showToast('Supabase belum dikonfigurasi. Isi supabase-config.js terlebih dahulu.');return false}return true}
async function loadAll(){
 if(!await requireConfigured()) return;
 try{
  const [p,g,a,k,m,r,ga]=await Promise.all([
   sb.from('profiles').select('*').limit(1).maybeSingle(), sb.from('groups').select('*').order('created_at'), sb.from('agenda').select('*').order('activity_date',{ascending:true}), sb.from('kegiatan_kua').select('*').order('activity_date',{ascending:false}), sb.from('materials').select('*').order('created_at',{ascending:false}), sb.from('reports').select('*').order('activity_date',{ascending:false,nullsFirst:false}), sb.from('gallery').select('*').order('created_at',{ascending:false})
  ]);
  for(const x of [p,g,a,k,m,r,ga]) if(x.error) throw x.error;
  cache={profile:p.data,groups:g.data||[],agenda:a.data||[],kegiatan_kua:k.data||[],materials:m.data||[],reports:r.data||[],gallery:ga.data||[]}; renderPublic();
 }catch(e){fail(e)}
}
function renderPublic(){
 const p=cache.profile||{};
 $('profileName').textContent=$('heroName').textContent=p.full_name||'Surianto, S.Ag'; $('profileStatus').textContent=$('heroStatus').textContent=p.status||'Penyuluh Agama Islam – PPPK'; $('profileKua').textContent=$('heroKua').textContent='◉ '+(p.kua||'Kec. Panca Lautang'); $('profileSk').textContent=p.sk_number||'2567/Kw.21.1/Kp.00.3/02/2025'; $('profileNip').textContent=p.nip||'—'; $('profileWa').textContent=p.whatsapp||'082132244214'; $('profileBio').textContent=p.bio||'Ruang digital untuk memperkuat pelayanan penyuluhan, dokumentasi kegiatan, materi dakwah, dan laporan KUA agar mudah diakses kapan saja.'; if(p.photo_url) $('profilePhotoHero').src=p.photo_url;
 $('groups').innerHTML=cache.groups.map((g,i)=>`<article class="group-card"><span class="num">KELOMPOK ${String(i+1).padStart(2,'0')}</span><h3>${esc(g.name)}</h3><div class="people">${g.participants} <small>orang</small></div>${g.description?`<p>${esc(g.description)}</p>`:''}</article>`).join('')||'<p>Belum ada kelompok.</p>';
 const total=cache.groups.reduce((s,g)=>s+Number(g.participants||0),0); $('groupTotal').textContent=total; $('statGroups').textContent=cache.groups.length; $('statParticipants').textContent=total; $('statMaterials').textContent=cache.materials.length;
 $('agendaList').innerHTML=cache.agenda.map(a=>`<article class="agenda-item"><div class="datebox"><b>${formatDay(a.activity_date)}</b><small>${formatMonth(a.activity_date)}</small></div><div><h3>${esc(a.title)}</h3><p>${[a.place,a.activity_time].filter(Boolean).map(esc).join(' • ')}</p>${a.description?`<small>${esc(a.description)}</small>`:''}</div></article>`).join('')||'<p>Belum ada agenda.</p>';
 renderKegiatanKua(); renderMaterials(); $('reports').innerHTML=`<table><thead><tr><th>No</th><th>Dokumen</th><th>Keterangan</th><th>File</th></tr></thead><tbody>${cache.reports.map((r,i)=>`<tr><td>${i+1}</td><td><b>${esc(r.title)}</b></td><td>${esc(r.description||[r.category,r.place,r.activity_date].filter(Boolean).join(' • '))}</td><td>${r.file_url?`<a class="read" href="${esc(r.file_url)}" target="_blank">Buka ↗</a>`:'—'}</td></tr>`).join('')}</tbody></table>`;
 renderGallery('all');
}
function renderKegiatanKua(){const list=cache.kegiatan_kua||[]; $('kegiatanKuaList').innerHTML=list.map(k=>`<article class="kua-news-card"><div class="kua-photo">${k.image_url?`<img src="${esc(k.image_url)}" alt="${esc(k.title)}">`:'<div class="kua-no-photo">Foto belum tersedia</div>'}</div><div class="kua-news-body"><div class="kua-meta">${k.activity_date?formatDate(k.activity_date):''}${k.place?` • ${esc(k.place)}`:''}</div><h3>${esc(k.title)}</h3><p>${esc(k.description||'')}</p></div></article>`).join('')||'<p>Belum ada kegiatan KUA.</p>'}
function formatDate(d){if(!d)return'';return new Date(d+'T00:00:00').toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'})}
function formatDay(d){if(!d)return'—';return new Date(d+'T00:00:00').getDate()}
function formatMonth(d){if(!d)return'';return new Date(d+'T00:00:00').toLocaleDateString('id-ID',{month:'short'}).toUpperCase()}
function renderMaterials(){const q=($('search').value||'').toLowerCase();$('materials').innerHTML=cache.materials.filter(m=>(m.title+' '+m.category+' '+(m.excerpt||'')+' '+(m.body||'')).toLowerCase().includes(q)).map(m=>`<article class="material"><span class="tag">${esc(m.category)}</span><h3>${esc(m.title)}</h3><p>${esc(m.excerpt||'')}</p><span class="read" onclick="readMaterial('${m.id}')">Baca materi →</span></article>`).join('')||'<p>Tidak ada materi yang cocok.</p>'}
window.renderMaterials=renderMaterials;
function renderGallery(f){$('gallery').innerHTML=cache.gallery.filter(x=>f==='all'||x.category===f).map(g=>`<div class="gallery-item" onclick="lightbox('${esc(g.image_url||'')}','${esc(g.title)}')"><img src="${esc(g.image_url||'assets/logo-kemenag-panca-lautang.png')}" alt="${esc(g.title)}"><div class="caption">${esc(g.title)}</div></div>`).join('')||'<p>Belum ada foto.</p>'}
function filterGallery(f,b){document.querySelectorAll('.gallery-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderGallery(f)} window.filterGallery=filterGallery;
function lightbox(src,title){const m=document.createElement('div');m.className='modal open';m.innerHTML=`<div class="modal-box" style="max-width:850px"><button class="close">×</button><img src="${src}" alt="${title}" style="width:100%;max-height:75vh;object-fit:contain;border-radius:14px"><p style="font-weight:800">${title}</p></div>`;m.querySelector('.close').onclick=()=>m.remove();document.body.appendChild(m)} window.lightbox=lightbox;
function readMaterial(id){const m=cache.materials.find(x=>x.id===id);if(!m)return;$('readTitle').textContent=m.title;$('readBody').textContent=m.body||m.excerpt||'Belum ada isi materi.';const a=$('readFile');if(m.file_url){a.href=m.file_url;a.classList.remove('hidden')}else a.classList.add('hidden');$('readModal').classList.add('open')} window.readMaterial=readMaterial;

async function login(){if(!await requireConfigured())return;const email=$('adminEmail').value.trim(),password=$('adminPass').value;if(!email||!password)return showToast('Email dan password wajib diisi.');try{const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;const ok=await isAdmin(data.user);if(!ok){await sb.auth.signOut();throw new Error('Akun ini belum terdaftar sebagai admin di tabel profiles.');}closeLogin();await openAdmin(data.user)}catch(e){fail(e)}} window.login=login;
async function isAdmin(user){const {data,error}=await sb.from('profiles').select('role').eq('id',user.id).maybeSingle();if(error)throw error;return data?.role==='admin'}
async function openAdmin(user){$('adminUserLabel').textContent=user.email;await refreshDashboard();$('adminModal').classList.add('open');showAdminTab('content',document.querySelector('.admin-tabs button'))}
async function logout(){if(sb)await sb.auth.signOut();closeAdmin();showToast('Anda telah keluar.')} window.logout=logout;
async function refreshDashboard(){await loadAll();$('dGroups').textContent=cache.groups.length;$('dParticipants').textContent=cache.groups.reduce((s,g)=>s+Number(g.participants||0),0);$('dAgenda').textContent=cache.agenda.length;$('dKegiatanKua').textContent=cache.kegiatan_kua.length;$('dMaterials').textContent=cache.materials.length;$('dReports').textContent=cache.reports.length;$('dGallery').textContent=cache.gallery.length;renderAdminItems();fillProfileForm()}
function showAdminTab(tab,b){document.querySelectorAll('.admin-tabs button').forEach(x=>x.classList.remove('active'));b?.classList.add('active');['adminContent','adminProfile','adminUpload','contentFormWrap'].forEach(x=>$(x).classList.add('hidden'));({content:'adminContent',profile:'adminProfile',upload:'adminUpload'})[tab]&&$( {content:'adminContent',profile:'adminProfile',upload:'adminUpload'}[tab]).classList.remove('hidden')}
window.showAdminTab=showAdminTab;
function renderAdminItems(){const type=$('contentType').value,items=cache[type]||[];$('adminItems').innerHTML=items.map(x=>`<div class="admin-row"><div><b>${esc(x.name||x.title)}</b><small>${esc(x.category||x.place||x.description||'')}</small></div><div><button onclick="editContent('${type}','${x.id}')">Edit</button><button class="danger" onclick="deleteContent('${type}','${x.id}')">Hapus</button></div></div>`).join('')||'<p>Belum ada data.</p>'}
window.renderAdminItems=renderAdminItems;
const fields={groups:[['name','Nama kelompok','text',true],['participants','Jumlah peserta','number',true],['description','Keterangan','textarea',false]],agenda:[['title','Judul','text',true],['activity_date','Tanggal','date',true],['activity_time','Waktu','text',false],['place','Tempat','text',false],['description','Keterangan','textarea',false]],materials:[['category','Kategori','text',true],['title','Judul','text',true],['excerpt','Ringkasan','textarea',false],['body','Isi materi','textarea',false],['file_url','URL file (opsional)','url',false],['file_name','Nama file','text',false],['published','Terbit','checkbox',false]],kegiatan_kua:[['title','Judul kegiatan','text',true],['activity_date','Tanggal','date',true],['place','Lokasi','text',false],['description','Berita / isi kegiatan','textarea',true],['image_url','URL foto','url',false],['file_name','Nama foto','text',false]],reports:[['title','Judul laporan','text',true],['category','Kategori','text',true],['activity_date','Tanggal','date',false],['place','Tempat','text',false],['description','Keterangan','textarea',false],['file_url','URL file','url',false],['file_name','Nama file','text',false]],gallery:[['title','Judul foto','text',true],['category','Kategori (penyuluh/kua)','text',true],['description','Keterangan','textarea',false],['image_url','URL foto','url',false],['file_name','Nama file','text',false]]};
let editing=null;
function openContentForm(type=$('contentType').value,item=null){editing=item?{type,id:item.id}:null;$('contentFormWrap').classList.remove('hidden');$('adminContent').classList.add('hidden');$('contentForm').innerHTML=(fields[type]||[]).map(([n,l,t,req])=>t==='textarea'?`<label class="span2">${l}<textarea name="${n}" rows="4" ${req?'required':''}></textarea></label>`:t==='checkbox'?`<label><input type="checkbox" name="${n}"> ${l}</label>`:`<label>${l}<input name="${n}" type="${t}" ${req?'required':''}></label>`).join('')+`<div class="span2"><button class="btn primary" type="submit">Simpan</button> <button type="button" class="small-btn" onclick="cancelContentForm()">Batal</button></div>`;const obj=item||{};for(const [n] of fields[type]){const el=$('contentForm').elements[n];if(el){if(el.type==='checkbox')el.checked=!!obj[n];else el.value=obj[n]??''}}$('contentForm').dataset.type=type}
window.openContentForm=openContentForm;
function cancelContentForm(){$('contentFormWrap').classList.add('hidden');$('adminContent').classList.remove('hidden');editing=null} window.cancelContentForm=cancelContentForm;
function editContent(type,id){const item=cache[type].find(x=>x.id===id);openContentForm(type,item)} window.editContent=editContent;
async function deleteContent(type,id){if(!confirm('Hapus data ini?'))return;try{const {error}=await sb.from(type).delete().eq('id',id);if(error)throw error;showToast('Data dihapus.');await refreshDashboard()}catch(e){fail(e)}} window.deleteContent=deleteContent;
$('contentForm').addEventListener('submit',async e=>{e.preventDefault();try{const type=e.currentTarget.dataset.type,fd=new FormData(e.currentTarget),obj={};for(const [k,v] of fd.entries())obj[k]=v;if((fields[type]||[]).some(f=>f[0]==='published'))obj.published=fd.has('published');for(const [n,l,t] of fields[type])if(t==='number'&&obj[n]!==undefined)obj[n]=Number(obj[n]);let q;if(editing)q=await sb.from(type).update(obj).eq('id',editing.id);else q=await sb.from(type).insert(obj);if(q.error)throw q.error;showToast('Data berhasil disimpan.');cancelContentForm();await refreshDashboard()}catch(e){fail(e)}});
function fillProfileForm(){const p=cache.profile||{};for(const n of ['full_name','status','kua','sk_number','nip','whatsapp','photo_url','bio'])$('profileForm').elements[n].value=p[n]||''}
$('profileForm').addEventListener('submit',async e=>{e.preventDefault();try{const {data:{user}}=await sb.auth.getUser();if(!user)throw new Error('Sesi login berakhir.');const fd=new FormData(e.currentTarget),obj=Object.fromEntries(fd.entries());obj.id=user.id;obj.role='admin';const q=await sb.from('profiles').upsert(obj);if(q.error)throw q.error;showToast('Profil disimpan.');await refreshDashboard()}catch(e){fail(e)}});
$('uploadForm').addEventListener('change',e=>{if(e.target.name==='bucket') $('uploadPhotoTypeWrap').style.display=e.target.value==='gallery'?'flex':'none'});
$('uploadPhotoTypeWrap').style.display='flex';
$('uploadForm').addEventListener('submit',async e=>{e.preventDefault();try{const fd=new FormData(e.currentTarget),bucket=fd.get('bucket'),file=fd.get('file'),label=fd.get('label'),photoType=fd.get('photo_type')||'gallery';if(!file?.name)throw new Error('Pilih file.');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}-${safe}`;const up=await sb.storage.from(bucket).upload(path,file,{upsert:false});if(up.error)throw up.error;const {data}=sb.storage.from(bucket).getPublicUrl(path);showToast(`Upload berhasil: ${label}`);showToast(`URL publik siap digunakan pada data konten.`);if(bucket==='gallery'){if(photoType==='kegiatan_kua'){$('contentType').value='kegiatan_kua';openContentForm('kegiatan_kua',{title:label,activity_date:new Date().toISOString().slice(0,10),image_url:data.publicUrl,file_name:file.name})}else{$('contentType').value='gallery';openContentForm('gallery',{title:label,category:'kua',image_url:data.publicUrl,file_name:file.name})}}else if(bucket==='documents'){$('contentType').value='reports';openContentForm('reports',{title:label,category:'Laporan Kegiatan',file_url:data.publicUrl,file_name:file.name})}}catch(e){fail(e)}});

if(sb){sb.auth.onAuthStateChange(async(_event,session)=>{if(session){try{if(await isAdmin(session.user)){/* session retained */}}catch(e){console.warn(e)}}})}
loadAll();
